//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourCrow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATING
    {
        public int RatingID { get; set; }
        public int UserID { get; set; }
        public int PlaceID { get; set; }
        public Nullable<double> Rating1 { get; set; }
        public int USERUserID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
