//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourCrow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourCrowEntities1 : DbContext
    {
        public TourCrowEntities1()
            : base("name=TourCrowEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMMENT> COMMENTs { get; set; }
        public DbSet<PACKAGE> PACKAGEs { get; set; }
        public DbSet<RATING> RATINGs { get; set; }
        public DbSet<USER> USERs { get; set; }
        public DbSet<USER_PACKAGE> USER_PACKAGE { get; set; }
    }
}
